<div id="modal-content">
    <?php
    $parentCategory = $block->getMainCategory();
    ?>
    <div class="field llantas_marca required">
        <label class="label" for="llantas_marca"><span><?php echo __('Seleccione su marca') ?></span></label>
        <div class="control">
            <?php
            foreach ($parentCategory as $parent) {
                if ($parent->hasChildren()) {
                    $parentObj = $block->getCategoryById($parent->getId());
                    ?>
                    <select name="llantas_marca" id="llantas_marca" title="<?php echo __('Seleccione su marca') ?>"
                            class="input-text"
                            data-validate="{required:true}">
                        <option value=""><?php echo __('Seleccione una opción') ?></option>
                        <?php
                        $childCategories = $parentObj->getChildrenCategories();
                        foreach ($childCategories as $child):
                            $childObj = $block->getCategoryById($child->getId());
                            ?>
                            <option value="<?php echo $child->getId() ?>"><?php echo $childObj->getName() ?></option>
                        <?php
                        endforeach;
                        ?>
                    </select>
                    <?php
                }
            }
            ?>
        </div>
    </div>
    <div class="field llantas_modelo required">
        <label class="label" for="llantas_modelo"><span><?php echo __('Seleccione un modelo') ?></span></label>
        <div class="control">
            <select name="llantas_modelo" id="llantas_modelo" title="<?php echo __('Seleccione un modelo') ?>"
                    class="input-text"
                    data-validate="{required:true}">
                <option value=""><?php echo __('Seleccione una opción') ?></option>
            </select>
        </div>
    </div>
    <div class="field llantas_ano required">
        <label class="label" for="llantas_ano"><span><?php echo __('Seleccione un año') ?></span></label>
        <div class="control">
            <select name="llantas_ano" id="llantas_ano" title="<?php echo __('Seleccione un año') ?>"
                    class="input-text"
                    data-validate="{required:true}">
                <option value=""><?php echo __('Seleccione una opción') ?></option>
            </select>
        </div>
    </div>
    <div id="compatible-options" style="text-align: center;">
        <br/>
        <h4>Opciones:</h4>
        <br/>
        <table id="compatible-table">
            <tr>
                <th>Diametro</th>
                <th>Ancho</th>
                <th>ET</th>
                <th>Buje</th>
            </tr>
        </table>
    </div>
</div>
<button type="button" id="configcar-modal-button" class="btn btn-primary">Configurador de Coche</button>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal',
            'domReady',
            'mage/cookies'
        ],
        function ($, modal) {
            $(document).ready(function () {
                $('#configcar-modal-button').html($.cookie('llantas_user_text'));
            });
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Configurador de coche',
                buttons: [{
                    text: $.mage.__('Select'),
                    class: 'accept',
                    click: function () {
                        $.cookie('llantas_user_car', ($('#llantas_ano option:selected').val()));
                        $.cookie('llantas_user_text', ($('#llantas_marca option:selected').text() + ' '
                            + $('#llantas_modelo option:selected').text() + ' ' + $('#llantas_ano option:selected').text()))
                        $('#configcar-modal-button').html($.cookie('llantas_user_text'));
                        this.closeModal();
                    }
                },
                    {
                        text: $.mage.__('Delete'),
                        class: 'delete',
                        click: function () {
                            $.cookie('llantas_user_car', null);
                            $.cookie('llantas_user_text', 'Configurador de coche');
                            $('#configcar-modal-button').html('Configurador de coche');
                            this.closeModal();
                        }
                    }]
            };
            let popup = modal(options, $('#modal-content'));
            $("#configcar-modal-button").click(function () {
                $('#modal-content').modal('openModal');
            });
            $("#llantas_ano").on('change', function () {
                $('.accept').prop('disabled', !$(this).val());
            }).trigger('change');
            $(document).on('change', '#llantas_marca', function () {
                var param = 'frame=' + $('#llantas_marca').val();
                $.ajax({
                    showLoader: true,
                    url: '<?php echo $block->getframeAction(); ?>',
                    data: param,
                    type: "GET",
                    dataType: 'json'
                }).done(function (data) {
                    jQuery('#llantas_modelo').empty();
                    jQuery('#llantas_ano').empty();
                    jQuery('#llantas_ano').append('<option selected="selected" value="">Seleccione una opción</option>');
                    jQuery('#llantas_modelo').append(data.value);
                });
            });

            $(document).on('change', '#llantas_modelo', function () {
                var param = 'frame=' + $('#llantas_modelo').val();
                $.ajax({
                    showLoader: true,
                    url: '<?php echo $block->getframeAction(); ?>',
                    data: param,
                    type: "GET",
                    dataType: 'json'
                }).done(function (data) {
                    jQuery('#llantas_ano').empty();
                    jQuery('#llantas_ano').append(data.value);
                });
            });

            $(document).on('change', '#llantas_ano', function () {
                var param = 'frame=' + $('#llantas_ano').val();
                $.ajax({
                    showLoader: true,
                    url: '<?php echo $block->getCategoriesAttributes(); ?>',
                    data: param,
                    type: "GET",
                    dataType: 'json'
                }).done(function (data) {
                    jQuery('#compatible-options').empty();
                    jQuery('#compatible-options').append(data.value);
                });
            });
        }
    );

</script>
