<?php

$product = $block->getProduct();
$attributeOptions = ['diameter', 'width', 'offset', 'hub', 'mounting', 'load'];
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$categoriesIds = $product->getCategoryIds();
$finish = '';
$dataCategories = '';
foreach ($categoriesIds as $categoryId)  {
    $category = $objectManager->create('Magento\Catalog\Model\Category')->load($categoryId);
    $dataCategories .= $category->getName() . ",";
}
?>
<div class="improved-products-description" id="categories" data-categories="<?php echo substr($dataCategories, 0, -1) ?>">
    <br>
    <h2><?php echo $product->getName(); ?> </h2>
    <br/>
    <h4 class="product-description"><?php echo $product->getDescription(); ?></h4>
    <br/>
    <h4>Opciones:</h4>
    <br/>
    <table class="compatible-table">
        <tr>
            <th>Diametro</th>
            <th>Ancho</th>
            <th>ET</th>
            <th>Buje</th>
            <th>Montaje</th>
            <th>Índice de Carga</th>
        </tr>
        <?php
        if ($product->getTypeId() == "simple") {
            ?>
            <tr>
                <?php
                foreach ($attributeOptions as $option) {
                    ?>
                    <th id="attribute-option"><?php echo $product->getAttributeText($option); ?></th>
                    <?php
                }
                $finish = $product->getAttributeText('variation');
                ?>
            </tr>
            <?php
        } else {
            $children = $product->getTypeInstance()->getUsedProducts($product);
            foreach ($children as $child) {
                ?>
                <tr>
                    <?php
                    foreach ($attributeOptions as $option) {
                        ?>
                        <th id="attribute-option"><?php echo $child->getAttributeText($option); ?></th>
                        <?php
                    }
                    ?>
                    <?php
                    $finish = $child->getAttributeText('variation');
                    ?>
                </tr>
                <?php
            }
        }
        ?>
    </table>
    <br/>
    <?php if ($finish) : ?>
        <h4> Acabado: <?php echo $finish ?></h4>
    <?php endif; ?>
</div>
