<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$cookieManager = $objectManager->get('Magento\Framework\Stdlib\CookieManagerInterface');
$carText = $cookieManager->getCookie('llantas_user_text');
$categoryId = $cookieManager->getCookie('llantas_user_car');
$carBrand = $cookieManager->getCookie('llantas_user_brand');
$carModel = $cookieManager->getCookie('llantas_user_model');
$carYear = $cookieManager->getCookie('llantas_user_year');
$variations = null;
$blockData = $block->getData();
if (array_key_exists('data', $blockData)) {
    if (array_key_exists('categoryId', $blockData['data'])) {
        $categoryId = $blockData['data']['categoryId'];
    }
    if (array_key_exists('validText', $blockData['data'])) {
        $carText = $blockData['data']['validText'];
    }
    $variations = $blockData['data']['validVariations'];
}
if ($carText === $carBrand . ' ' . $carModel . ' ' . $carYear):
    ?>
    <h4 id="car-name"><?php echo $carText ?></h4>
<?php
endif;
?>
</br>
<?php if ($variations):
    $data = ['validVariations' => json_decode($variations)];
    echo $this->getLayout()->createBlock("Comerline\ConfigCar\Block\ConfigCar")->setTemplate("Comerline_ConfigCar::product/view/compatible-table.phtml")->setData('data', $data)->toHtml();
endif;
?>
