<?php
$blockData = $block->getData();
if (array_key_exists('data', $blockData)) {
    $categoryId = $blockData['data']['categoryId'];
}
?>
<option value=""><?php echo __('Seleccione una opción') ?></option>
<?php
if (isset($categoryId)):
    $category = $block->getCategoryById($categoryId);
    $childrenCategories = $category->getChildrenCategories();
    foreach ($childrenCategories as $children) {
        ?>
        }
        <option value="<?php echo $children->getId(); ?>"><?php echo $children->getName(); ?></option>
        <?php
    }
endif;
?>
