<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$cookieManager = $objectManager->get('Magento\Framework\Stdlib\CookieManagerInterface');
$cookie = $cookieManager->getCookie('llantas_user_car');
$carBrand = $cookieManager->getCookie('llantas_user_brand');
$carModel = $cookieManager->getCookie('llantas_user_model');
$carYear = $cookieManager->getCookie('llantas_user_year');
$category = null;
$comparableAttributes = ['diameter', 'width', 'offset', 'hub'];
if ($cookie) :
    $category = $block->getCategoryById($cookie);
endif;
if ($category):
    $productCollection = $block->getProductCollectionByCategories(array($cookie));
    $categoryProduct = $productCollection->getFirstItem();
    $currentProduct = $block->getCurrentProduct();
    $valid = 0;
    $validVariations = [];
    ?>

    <div id="compatible-rims">
        <?php
        if ($currentProduct->getTypeId() == "simple") {
            $validVariations = array_merge($validVariations, $block->compareProductAttributes($currentProduct, $carBrand, $carModel, $carYear));
            if ($validVariations) {
                ?>
                <p id="green"> <?php echo __('Esta llanta es compatible con tu vehículo') ?> </p>
                <?php
            } else {
                ?>
                <p id="red"> <?php echo __('Esta llanta no es compatible con tu vehículo') ?> </p>
                <?php
            }
        } else {
            $children = $currentProduct->getTypeInstance()->getUsedProducts($currentProduct);
            foreach ($children as $child) {
                $validVariations = array_merge($validVariations, $block->compareProductAttributes($child, $carBrand, $carModel, $carYear));
            }
            $validVariations = array_unique($validVariations);
            if ($validVariations) {
                ?>
                <p id="green"
                   class="compatible"> <?php echo __('Esta llanta tiene variaciones compatibles con tu vehículo') ?> </p>
                <div id="compatibles">
                    <?php
                        $data = ['validVariations' => $validVariations];
                    echo $this->getLayout()->createBlock("Comerline\ConfigCar\Block\ConfigCar")->setTemplate("Comerline_ConfigCar::product/view/comparable-attributes.phtml")->setData('data', $data)->toHtml();
                    ?>
                </div>
                <?php
            } else {
                ?>
                <p id="red"> <?php echo __('Esta llanta no tiene variaciones compatibles con tu vehículo') ?> </p>
                <?php
            }
        }
        ?>
    </div>

<?php
endif;
?>

<script>
    require(['jquery', 'showModal'], function ($, showModal) {
        showModal();
    });
</script>
